# Server Configuration
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:h2:file:./data/shopeease_final;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Static Resources - IMPORTANT FOR IMAGES
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**
spring.web.resources.add-mappings=true
# Add these lines to force DataLoader to run
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.main.allow-circular-references=true